{"content": {"suites": {"0": {"status": {"total_pass": 0, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 4, "total_error": 0}, "tests": {"0": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x102a79550>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=63993): Max retries exceeded with url: /session/8321cabea50b1ce4e023d63caf87cf7f/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x102a79550>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_login", "rerun": "0"}, "1": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x102dfa040>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=63993): Max retries exceeded with url: /session/8321cabea50b1ce4e023d63caf87cf7f/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x102dfa040>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_bandcreate", "rerun": "0"}, "2": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x102dab9d0>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=63993): Max retries exceeded with url: /session/8321cabea50b1ce4e023d63caf87cf7f/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x102dab9d0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_bandwrite", "rerun": "0"}, "3": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 61] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x102c2d670>: Failed to establish a new connection: [Errno 61] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=63993): Max retries exceeded with url: /session/8321cabea50b1ce4e023d63caf87cf7f/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x102c2d670>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "test_name": "test_postedit", "rerun": "0"}}, "suite_name": "main.py"}}}, "date": "February 15, 2024", "start_time": 1707987371.1746829, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "0", "fail": "4", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "4"}